---
# tasks
    - name: install  package ubuntu
      environment:
        http_proxy: "{{ proxy }}"
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - net-tools
        - ntp
        - ntpdate
        - python
        - python-simplejson
        - apt-transport-https
        - software-properties-common
        - tree
