---
- hosts: all
sudo: yes
roles:
  - { role: "fab.debupdate" }
  - { role: "fab.debsources" }
  - { role: "fab.debcommon" }
  - { role: "fab.confntp" }
  - { role: "fab.libsdl" }
  - { role: "fab.testvars" }

