---
# tasks file for fab.servernfs
  - name: install nfs package debian
    environment:
      http_proxy: http://192.168.4.60:3128/
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - nfs-kernel-server
      - ntfs-3g