version: '2'
services:
  rancher-server:
    image: rancher/server:stable
    restart: unless-stopped
    command: --db-host {{DBHOST}} --db-port 3306 --db-name cattle --db-user cattle --db-pass "cattle" --advertise-address {{ADRIP}} --advertise-http-port {{SERVERPORT}}
    volumes:
      - /USR/data/rancher/logs:/var/log
      - /USR/data/rancher/lib:/var/lib/rancher
    ports:
      - {{SERVERPORT}}:8080
      - 9345:9345

