---
# tasks file for fab.debupdate
  
  - name: APT UPDATE
    become: true
    environment:
      http_proxy: "{{ proxy }}"
    apt:
      update_cache: yes
    when: (ansible_distribution|lower == "debian" or ansible_distribution|lower == "ubuntu")

