---
# tasks
    - name: installation SDL  package debian/Ubuntu
      environment:
        http_proxy: http://192.168.4.60:3128/
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libsdl1.2debian
        - libsdl1.2-dev
        - libsdl-image1.2
        - libsdl-image1.2-dev
        - libsdl-mixer1.2
        - libsdl-mixer1.2-dev
        - libsdl-ttf2.0-0
        - libsdl-ttf2.0-dev
      when: ( 1.2 == SDLVERSION )
