---
# tasks file for rancher.install_docker.ubuntu

  - name: Add an Apt signing key, uses whichever key is at the URL
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Recuperer la release Ubuntu
    shell: "lsb_release -cs"
    register: release_version

  - name: Ajoute le repository docker
    become: true
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{release_version.stdout}} stable"
      state: present

  - name: Update du cache
    become: true
    apt:
      update_cache: yes

  - name: installe docker ce
    become: true
    apt:
      name: docker-ce=18.06.1~ce~3-0~ubuntu
      state: present

  - name: Installe pyhton-pip
    become: true
    apt:
      name: python-pip
      state: present

  - name: Install docker compose
    become: true
    shell: "pip -q install docker-compose"

  - name: lance docker
    become: true
    service: 
      name: docker
      state: restarted


